/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chemproject;



import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aadhithya
 */
public class Form2 extends javax.swing.JFrame {

    /**
     * Creates new form Form2
     */
    Connection con;
    Statement sta;
    public Form2() {
        initComponents();
         try{
             Class.forName("org.apache.derby.jdbc.EmbeddedDriver");
             
             con=DriverManager.getConnection("jdbc:derby:chem;create=true");
             sta=con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,
                    ResultSet.CONCUR_READ_ONLY);
             /*sta.execute("CREATE TABLE metal (" +
"  name varchar(25) NOT NULL," +
"  chem varchar(7) NOT NULL," +
"  molarmass varchar(7) NOT NULL," +
"  bandgap decimal(10,4) NOT NULL," +
"  description varchar(80) DEFAULT NULL," +
"  PRIMARY KEY (name)\n" +
")");*/
            // sta.execute("INSERT INTO metal VALUES ('Aluminium(III) Oxide','Al2O3','101.96',6.9600,'white solid ,odourless'),('Barium oxide','BaO','153.32',5.2000,'white solid'),('Beryllium(II) monoxide','BeO','25.01',10.6000,'Colourless, vitreous crystals, Odourless'),('BorontriOxide','B2O3','69.618',8.4500,'white , glassy solid'),('Cadmium oxide','CdO','128.41',2.5000,'colorless powder(alpha) red-brown crystal(beta) , odourless'),('Calcium Oxide','CaO','56.077',6.2600,'white -> pale yellow/brown pow.,odourles'),('Cerium(IV) oxide','CeO2','172.11',3.7800,'white or pale yellow solid,slightly hygroscopic'),('Chromium(III) Oxide','Cr2O3','151.99',2.5800,'light to dark green,fine crystals'),('Cobalt(II) oxide','CoO','74.932',3.2000,'black powder , odourless'),('Copper(I) oxide','Cu2O','143.09',2.0400,'brownish-red solid'),('Europium oxide','Eu2O3','351.92',4.3000,'white powder'),('Gallium(III) oxide','Ga2O3','187.44',5.4000,'white crystalline powder'),('Germanium dioxide','GeO2','104.638',5.3500,'white powder or colourless crystals'),('Indium(III) oxide','In2O3','277.64',3.5500,'yellowish green odorless crystals'),('Iron(II) oxide','FeO','71.844',3.2000,'black crystals'),('Lanthanum(III) oxide','La2O3','325.80',5.5000,'white powder hygroscopic'),('Magnesium Oxide','MgO','40.304',7.8000,'white powder , odourless'),('Manganese(II) oxide','MnO','70.937',4.0000,'green crystals or powder'),('Neodymium(III) oxide','Nd2O3','336.48',4.6000,'light bluish hexagonal gray crystals'),('Nickel(II) oxide','NiO','74.692',2.8600,'green crystalline solid'),('Praseodymium(III) oxide','Pr2O3','329.81',3.8000,'white hexagonal crystals'),('Strontium oxide','SrO','103.61',6.5000,'colourless cubic crystals'),('Tin dioxide','SnO2','150.71',3.5700,'white or light grey powder'),('Titanium diOxide','TiO','79.866',3.6000,'white solid ,odourless'),('Zinc oxide','ZnO','81.38',3.3000,'white solid odourless')");
             String sa="Select name from metal";
             ResultSet rs=sta.executeQuery(sa);
             DefaultTableModel tb1=(DefaultTableModel)jTable1.getModel();
             rs.first();
             String nm=rs.getString("name");
             Object row[]={nm};
             tb1.addRow(row);
             while(rs.next()){
                nm=rs.getString("name");
                Object row1[]={nm};
                tb1.addRow(row1);
             }
             
         }
         catch(Exception ex){
             JOptionPane.showMessageDialog(this,ex.getMessage());
         }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        l2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        l5 = new javax.swing.JTextArea();
        l3 = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        l2.setFont(new java.awt.Font("Ubuntu", 1, 17)); // NOI18N
        l2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chemical Formula", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 18))); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Metal Oxides"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setColumnSelectionAllowed(true);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        l5.setEditable(false);
        l5.setColumns(15);
        l5.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        l5.setLineWrap(true);
        l5.setRows(5);
        l5.setWrapStyleWord(true);
        l5.setAutoscrolls(false);
        l5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Description", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 18))); // NOI18N
        jScrollPane2.setViewportView(l5);

        l3.setFont(new java.awt.Font("Ubuntu", 1, 17)); // NOI18N
        l3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Molecular Mass", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 18))); // NOI18N

        l1.setFont(new java.awt.Font("Ubuntu", 1, 17)); // NOI18N
        l1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Name", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 18))); // NOI18N

        l4.setFont(new java.awt.Font("Ubuntu", 1, 17)); // NOI18N
        l4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Band Gap", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 18))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l2, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l3, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l4, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(7, 7, 7))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(l2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(l3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(l4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
  
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        try {
            // TODO add your handling code here:
            int sel=jTable1.getSelectedRow();
            Object row=jTable1.getValueAt(sel,0);
            String nm=row.toString();
            nm="Select * from metal where name='"+nm+"'";
            ResultSet rs=sta.executeQuery(nm);
            rs.first();
            l1.setText(rs.getString("name"));
            l2.setText(rs.getString("chem"));
            l3.setText(rs.getString("molarmass"));
            Float bg=rs.getFloat("bandgap");
            l4.setText(bg.toString());
            l5.setText(rs.getString("description"));
        } catch (SQLException ex) {
            Logger.getLogger(Form2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JTextArea l5;
    // End of variables declaration//GEN-END:variables
}
